# fly.toml app configuration file generated for glixera-affiliate on 2026-08-17T21:17:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'glixera-affiliate'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '10s'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATA_DIR = '/data'
  NODE_ENV = 'production'
  PORT = '8080'
  TIME_ZONE = 'Europe/Brussels'

[[mounts]]
  source = 'affiliate_data'
  destination = '/data'
  initial_size = '1GB'

[checks.health]
  type = 'http'
  port = 8080
  grace_period = '20s'
  interval = '30s'
  method = 'GET'
  path = '/health'
  timeout = '5s'

[[restart]]
  policy = 'on-failure'
  retries = 10

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
